## Author: Indranil Ghosh, Jadavpur University, Physics Department

PWM <- array(c(0.6, 0.4, 0, 0, 0.25, 0.25, 0.25, 0.25, 0.10, 0.10, 0.40, 0.40, 1.0, 0, 0, 0), dim=c(4, 4)) #PWM represents the Position Weight Matrix
PWM <- as.data.frame(A)
rownames(PWM) <- c('A','G','T','C')
BD <- array(c(0.1, 0.4, 0.1, 0.4), dim=c(4, 1)) #BD represents the Background Distribution of nucleotides
rownames(BD) <- c('A','G','T','C')
PWM
BD
P_M <- 0.3
S <- c('G', 'A', 'C', 'A')

P <- function(S, PWM, BD, P_M) {
  P_SM <- 1 # Probability of the motif generating the sequence
  P_SB <- 1 # Probability of the background generating the sequence
  #P_M <- Probability of sequences generated by the motif
  P_B <- 1-P_M # Probability of sequences generated by the background
  for (i in 1:length(S)){
    P_SM <- P_SM*PWM[[S[i], i]]
    P_SB <- P_SB*BD[[S[i], 1]]
  }
  P_MS <- P_SM*P_M/(P_SB*P_B+P_SM*P_M) # Using the Bayes' rule
  D <- array(c(P_M, P_B, P_SM, P_SB, P_MS, 1-P_MS), dim=c(1, 6))
  D <- as.data.frame(D)
  colnames(D) <- c('P(M)', 'P(B)', 'P(S|M)', 'P(S|B)', 'P(M|S)', 'P(B|S)')
  return(D)
}
P(S, PWM, BD, P_M)

